### PR TITLE
Login within game#25

### PR DESCRIPTION
**Pull request by marmohamed**

### CODE REVIEW

**Comment by marmohamed** [comment]
@NadineMansour  @MMelouk94 @mohamadbadr  @alisoliman

**Comment by marmohamed** [comment]
External Documentation:
The user has to login within the game to identify them and keep track of their info.
The user enter email, password in 2 input fields.
If the user clicks the login button, an https request is sent to the api/records#user_login with email and password as post parameters.
If the response is OK, go to the next scene, else the text in the input field will be cleared to allow the user to enter valid email and password

**Comment by marmohamed** [comment]
logingame

**Comment by MMelouk** [comment]
@MariamMohamedFawzy There are conflicts, can't be merged. Fix conflicts first.

**Pull request closed without merging**
